---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.12.2021 22:33

ETCUnits = {}
perebor = CreateGroup()
function InitEtcGroup()
    local id = { FourCC("h001"), FourCC("h002"), FourCC("h003"), FourCC("h004"), FourCC("h005"), FourCC("h006") } ---01-06
    local e = nil


    GroupEnumUnitsInRect(perebor, bj_mapInitialPlayableArea, nil)

    --GroupEnumUnitsInRange(perebor, 0, 0, 8000, nil)

    while true do
        e = FirstOfGroup(perebor)
        --print(GetUnitName(e), " в переборе")
        if e == nil then
            --print("перебор группы завершен")
            break
        end
        if UnitAlive(e) then
            --print(GetUnitName(e)," в переборе")
            if GetAnyInTable(id, GetUnitTypeId(e)) then
                -- print(GetUnitName(e),"добавлен в etc")
                table.insert(ETCUnits, e)
            end
        end
        GroupRemoveUnit(perebor, e)
        --print("remove")
    end
end

function GetAnyInTable(sort, element)
    local is, any = nil, nil
    for i = 1, #sort do
        if sort[i] == element then
            --print("Элемент", element, "содержится в этой таблице")
            is = true
            --table.remove(sort, FinPosInTable(sort, element))
        end
    end
    any = sort[GetRandomInt(1, #sort)]
    --print("вернул",any)
    return is, any
end

function ETCPlay(state)
    for i = 1, #ETCUnits do
        if state then
            SetUnitAnimation(ETCUnits[i], "Spell")
        else
            SetUnitAnimation(ETCUnits[i], "Stand")
        end
    end
end

function FinPosInTable(t, f)
    local pos = 0
    for i = 1, #t do
        if t[i] == f then
            pos = i
            return pos
        end
    end
    --print(pos)
    return pos
end