---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.11.2021 15:57
---
do
    GameStartCount=0
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()

        TimerStart(CreateTimer(), 1, false, function()
            DestroyTimer(GetExpiredTimer())
            InitPreloadStartSimple()
            SaveResult(math.floor(GameStartCount + 1))
        end)
    end
end

function InitPreloadStartSimple()
    SavePath = "save\\TestGameStart.txt" --путь до файла что мы формировали
    Preloader(SavePath) --в этот момент данные записываются в имя способности, для каждого игрока свои данные
    GameStartCount = BlzGetAbilityTooltip(FourCC('Agyv'), 0)
    if tonumber(GameStartCount) then
        -- код может быть числом
        print("Сыграно игр "..GameStartCount)
    else
        print("Первая игра")
        GameStartCount=0
    end
end

function SaveResult(SaveCode)
    Preload("\")\ncall BlzSetAbilityTooltip ('Agyv',\"" .. SaveCode .. "\",0)" .. "\n//")
    PreloadGenEnd(SavePath)
    PreloadGenClear()
end