---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.11.2021 2:06
---
SongTrigger={}
function StartSong()
    --normal_sound("AllForce") --играем музыку
    ClearMapMusicBJ()
    PlayMusicBJ("AllForce")
    SetMusicVolumeBJ(100)
    for i=1,#BoPeeBoNormal do
        EnableTrigger(SongTrigger[i])
        TriggerExecute(SongTrigger[i])
        print("запускаем", i)
    end
end

function InitSonTrigger()
        for i, delay in ipairs(BoPeeBoNormal) do
        SongTrigger[i] = CreateTrigger()
            print("создан триггер",i)
        DisableTrigger(SongTrigger[i] )
        TriggerRegisterTimerEventSingle(SongTrigger[i], 0.)
        TriggerAddAction(SongTrigger[i] , function()
            TriggerSleepAction(delay)
            print(delay)
            DisableTrigger(GetTriggeringTrigger())
        end)
    end
end