gg_trg_Init = nil
gg_trg_StartTest = nil
function InitGlobals()
end

BoPeeBoNormal={ --*0.6
    0,0.6,2.4,3,4.8,5.4,6,7.2,7.8,8.4,9.6,10.2,10.5,10.8,12,12.6,12.9,13.2,14.4,14.7,15,15.3,15.6,16.8,17.1,17.4,17.7,18,19.2,19.5,19.8,21.6,21.9,22.2,24,24.3,24.6,26.4,26.7,27,28.8,29.1,29.4,31.2,31.5,31.8,33.3,33.6,33.9,34.5,34.8,35.7,36,36.3,36.9,37.2,38.4,39,39.6,40.8,41.4,42,43.2,43.8,44.4,44.55,44.7,45,45.6,46.2,46.8,46.95,47.1,47.4,48,48.6,49.2,50.4,51,51.6,52.8,55.2,57.6,57.9,58.2,60,60.3,60.6,62.1,62.4,62.7,63.3,63.6,64.5,64.8,65.1,65.7,66,67.2,67.5,67.8,68.1,68.4,69.6,69.9,70.2,70.5,70.8,71.7,72,72.3,72.9,73.2,74.1,74.4,74.7,75.3,75.6,
}
function StartSong()
    --normal_sound("AllForce") --играем музыку
    ClearMapMusicBJ()
    PlayMusicBJ("AllForce")
    SetMusicVolumeBJ(100)
    for i = 1, #BoPeeBoNormal do
        local delay = BoPeeBoNormal[i]
        TimerStart(CreateTimer(), delay, false, function()
            print(delay)
            PauseTimer(GetExpiredTimer())
            DestroyTimer(GetExpiredTimer())
        end)
    end
end
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.05.2020 23:15
---
---
---
--[[
do
    local DestroyTimerOrigin = DestroyTimer -- записываем DestroyTimer в переменную
    local PauseTimerCached = PauseTimer -- локальная переменная используется для более быстрого вызова функции в дальнейшем
    function DestroyTimer(t)
        PauseTimerCached(t)  -- вызываем PauseTimer из переменной
        DestroyTimerOrigin(t) -- вызываем DestroyTimer из переменной
    end
end]]
local origDestroyTimer = DestroyTimer
function DestroyTimer(t)

    if t == nil then
        t = GetExpiredTimer()
        if t == nil then
            --print("в функцию разрушения таймера передано что-то не то")
            return
        end

    end
    PauseTimer(t)
    GCountTimers = GCountTimers - 1
    origDestroyTimer(t)
end

local realTimerStart = TimerStart
GCountTimers = 0
TimerStart = function(timer, duration, repeating, callback)
    local pcallback = function()
        if callback == nil then
            return
        end
        local status, err = pcall(callback)
        if not status then
            print(err)
        end
    end
    GCountTimers = GCountTimers + 1
    --print("Запущено таймеров", GCountTimers)
    realTimerStart(timer, duration, repeating, pcallback)
end

local realTriggerAddAction = TriggerAddAction
TriggerAddAction = function(trig, callback)
    local pcallback = function()
        local status, err = pcall(callback)
        if not status then
            print(err)
        end
    end
    realTriggerAddAction(trig, pcallback)
end

function normal_sound (s, x, y, volume)
    local snd = CreateSound(s, false, false, false, 10, 10, "")
    if not volume then
        volume = 127
    end
    if not x then
        x = 0
    end
      if not y then
        y = 0
    end
    SetSoundChannel(snd, 1)
    SetSoundVolume(snd, volume)
    StartSound(snd)
    --KillSoundWhenDone(snd)
    return snd
end
function CreateAndStartClock()

	local charges= BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	local new_FrameChargesText = BlzCreateFrameByType("TEXT", "ButtonChargesText", charges, "", 0)

	BlzFrameSetTexture(charges, "UI\\Widgets\\Console\\Human\\CommandButton\\human-button-lvls-overlay", 0, true)
	BlzFrameSetSize(charges, 0.08, 0.02)
	BlzFrameSetAbsPoint(charges, FRAMEPOINT_CENTER,0.48 , 0.6-0.01)
	--BlzFrameSetPoint(charges, FRAMEPOINT_BOTTOM, wood, FRAMEPOINT_BOTTOM, 0,0)
	BlzFrameSetText(new_FrameChargesText, Zero(0)..":"..Zero(0)..":"..Zero(0))
	BlzFrameSetPoint(new_FrameChargesText, FRAMEPOINT_CENTER, charges, FRAMEPOINT_CENTER, 0.,0.)
	local sec=0
	local min=0
	local h=0
	TimerStart(CreateTimer(), 1, true, function()
		sec=sec+1
		if sec==60 then
			sec=0
			min=min+1
		end
		if min==60 then
			min=0
			h=h+1
		end

		BlzFrameSetText(new_FrameChargesText, Zero(h)..":"..Zero(min)..":"..Zero(sec))
	end)
end

function Zero(s)
	local ns=""
	if string.len(s)==1 then
		ns="0"..s
	else
		ns=s
	end
	return ns
end
function Trig_Init_Actions()
        CreateAndStartClock()
end

function InitTrig_Init()
    gg_trg_Init = CreateTrigger()
    TriggerRegisterTimerEventSingle(gg_trg_Init, 0.01)
    TriggerAddAction(gg_trg_Init, Trig_Init_Actions)
end

function Trig_StartTest_Actions()
        StartSong()
end

function InitTrig_StartTest()
    gg_trg_StartTest = CreateTrigger()
    TriggerRegisterPlayerEventEndCinematic(gg_trg_StartTest, Player(0))
    TriggerAddAction(gg_trg_StartTest, Trig_StartTest_Actions)
end

function InitCustomTriggers()
    InitTrig_Init()
    InitTrig_StartTest()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), true)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
end

function main()
    SetCameraBounds(-1280.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 1280.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -1280.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 1280.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(1)
    SetTeams(1)
    SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)
    DefineStartLocation(0, -128.0, -448.0)
    InitCustomPlayerSlots()
    SetPlayerSlotAvailable(Player(0), MAP_CONTROL_USER)
    InitGenericPlayerSlots()
end

