gg_trg_Init = nil
gg_trg_StartTest = nil
gg_trg_Sleep = nil
function InitGlobals()
end

BoPeeBoNormal={ --*0.6
    0,0.6,2.4,3,4.8,5.4,6,7.2,7.8,8.4,9.6,10.2,10.5,10.8,12,12.6,12.9,13.2,14.4,14.7,15,15.3,15.6,16.8,17.1,17.4,17.7,18,19.2,19.5,19.8,21.6,21.9,22.2,24,24.3,24.6,26.4,26.7,27,28.8,29.1,29.4,31.2,31.5,31.8,33.3,33.6,33.9,34.5,34.8,35.7,36,36.3,36.9,37.2,38.4,39,39.6,40.8,41.4,42,43.2,43.8,44.4,44.55,44.7,45,45.6,46.2,46.8,46.95,47.1,47.4,48,48.6,49.2,50.4,51,51.6,52.8,55.2,57.6,57.9,58.2,60,60.3,60.6,62.1,62.4,62.7,63.3,63.6,64.5,64.8,65.1,65.7,66,67.2,67.5,67.8,68.1,68.4,69.6,69.9,70.2,70.5,70.8,71.7,72,72.3,72.9,73.2,74.1,74.4,74.7,75.3,75.6,
}
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.11.2021 2:06
---
SongTrigger={}
function StartSong()
    --normal_sound("AllForce") --играем музыку
    ClearMapMusicBJ()
    PlayMusicBJ("AllForce")
    SetMusicVolumeBJ(100)
    for i=1,#BoPeeBoNormal do
        EnableTrigger(SongTrigger[i])
        --TriggerExecute(SongTrigger[i])
        print("запускаем", i)
    end
end

function InitSonTrigger()
        for i, delay in ipairs(BoPeeBoNormal) do
        SongTrigger[i] = CreateTrigger()
            print("создан триггер",i)
        DisableTrigger(SongTrigger[i] )
        TriggerRegisterTimerEventPeriodic(SongTrigger[i], 0.)
        TriggerAddAction(SongTrigger[i] , function()
        DisableTrigger(GetTriggeringTrigger())
            TriggerSleepAction(delay)
            print(delay)
            
        end)
    end
end
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.05.2020 23:15
---
---
---
--[[
do
    local DestroyTimerOrigin = DestroyTimer -- записываем DestroyTimer в переменную
    local PauseTimerCached = PauseTimer -- локальная переменная используется для более быстрого вызова функции в дальнейшем
    function DestroyTimer(t)
        PauseTimerCached(t)  -- вызываем PauseTimer из переменной
        DestroyTimerOrigin(t) -- вызываем DestroyTimer из переменной
    end
end]]
local origDestroyTimer = DestroyTimer
function DestroyTimer(t)

    if t == nil then
        t = GetExpiredTimer()
        if t == nil then
            --print("в функцию разрушения таймера передано что-то не то")
            return
        end

    end
    PauseTimer(t)
    GCountTimers = GCountTimers - 1
    origDestroyTimer(t)
end

local realTimerStart = TimerStart
GCountTimers = 0
TimerStart = function(timer, duration, repeating, callback)
    local pcallback = function()
        if callback == nil then
            return
        end
        local status, err = pcall(callback)
        if not status then
            print(err)
        end
    end
    GCountTimers = GCountTimers + 1
    --print("Запущено таймеров", GCountTimers)
    realTimerStart(timer, duration, repeating, pcallback)
end

local realTriggerAddAction = TriggerAddAction
TriggerAddAction = function(trig, callback)
    local pcallback = function()
        local status, err = pcall(callback)
        if not status then
            print(err)
        end
    end
    realTriggerAddAction(trig, pcallback)
end

function CreateAndStartClock()

	local charges= BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	local new_FrameChargesText = BlzCreateFrameByType("TEXT", "ButtonChargesText", charges, "", 0)

	BlzFrameSetTexture(charges, "UI\\Widgets\\Console\\Human\\CommandButton\\human-button-lvls-overlay", 0, true)
	BlzFrameSetSize(charges, 0.08, 0.02)
	BlzFrameSetAbsPoint(charges, FRAMEPOINT_CENTER,0.48 , 0.6-0.01)
	--BlzFrameSetPoint(charges, FRAMEPOINT_BOTTOM, wood, FRAMEPOINT_BOTTOM, 0,0)
	BlzFrameSetText(new_FrameChargesText, Zero(0)..":"..Zero(0)..":"..Zero(0))
	BlzFrameSetPoint(new_FrameChargesText, FRAMEPOINT_CENTER, charges, FRAMEPOINT_CENTER, 0.,0.)
	local sec=0
	local min=0
	local h=0
	TimerStart(CreateTimer(), 1, true, function()
		sec=sec+1
		if sec==60 then
			sec=0
			min=min+1
		end
		if min==60 then
			min=0
			h=h+1
		end

		BlzFrameSetText(new_FrameChargesText, Zero(h)..":"..Zero(min)..":"..Zero(sec))
	end)
end

function Zero(s)
	local ns=""
	if string.len(s)==1 then
		ns="0"..s
	else
		ns=s
	end
	return ns
end
function InitEtcGroup()
    local id = { FourCC("h001"), FourCC("h002"), FourCC("h003"), FourCC("h004"), FourCC("h005"), FourCC("h006") } ---01-06
    local e = nil
    local perebor2 = CreateGroup()

    --GroupEnumUnitsInRect(perebor, bj_mapInitialPlayableArea, nil)

    local group = CreateGroup()
    GroupEnumUnitsInRange(group, 0, 0, 8000, nil)
    while true do
        local target = FirstOfGroup(group)
        print(GetUnitName(target),"в переборе")
        if target == nil then
            print("группа пуста")
            break
        end
        if UnitAlive(target) then
            print(GetUnitName(target))
        end
        GroupRemoveUnit(group, target)
    end
    --[[
    while true do
        e = FirstOfGroup(perebor2)
        print(GetUnitName(e), " в переборе")
        if e == nil then
            print("перебор группы завершен")
            break
        end
        if UnitAlive(e) then
            print(e)
            if GetAnyInTable(id, GetUnitTypeId(e)) then
                table.insert(ETCUnits, e)
            end
        end
        GroupRemoveUnit(perebor2, e)
        print("remove")
    end]]
end
function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -270.9, -112.9, 143.563, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -342.4, -173.8, 296.706, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -377.3, -177.6, 11.327, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -358.2, 55.4, 27.708, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -227.2, 229.9, 324.733, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -66.3, 142.6, 158.581, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), 69.7, -54.8, 190.223, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), 68.4, -193.9, 244.684, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -99.6, -219.9, 250.002, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -365.2, -50.7, 108.186, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -396.6, 236.6, 305.253, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -199.5, 409.2, 53.571, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), 51.9, 187.3, 198.639, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -113.7, -175.1, 241.663, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -206.9, 40.6, 185.839, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -70.0, 53.9, 299.167, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -57.0, -35.4, 244.651, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -89.9, -102.3, 109.493, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), -128.6, -76.7, 239.971, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 245.5, 31.8, 252.847, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 234.3, -104.9, 328.721, FourCC("hfoo"))
    u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 246.3, -276.4, 243.717, FourCC("hfoo"))
end

function CreatePlayerBuildings()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
end

function CreateAllUnits()
    CreatePlayerBuildings()
    CreatePlayerUnits()
end

function Trig_StartTest_Actions()
        InitEtcGroup()
end

function InitTrig_StartTest()
    gg_trg_StartTest = CreateTrigger()
    TriggerRegisterPlayerEventEndCinematic(gg_trg_StartTest, Player(0))
    TriggerAddAction(gg_trg_StartTest, Trig_StartTest_Actions)
end

function InitCustomTriggers()
    InitTrig_StartTest()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), true)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
end

function main()
    SetCameraBounds(-1280.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 1280.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -1280.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 1280.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(1)
    SetTeams(1)
    SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)
    DefineStartLocation(0, -128.0, -448.0)
    InitCustomPlayerSlots()
    SetPlayerSlotAvailable(Player(0), MAP_CONTROL_USER)
    InitGenericPlayerSlots()
end

