---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.10.2021 14:39
---
function ArthasDamage()
    UnitAddAbility(GEnemy, FourCC("A001"))
    TimerStart(CreateTimer(), 0.4, false, function()
        Damage(30)
        DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", GetUnitXY(GPlayer)))
    end)
    TimerStart(CreateTimer(), 0.6, false, function()
        UnitRemoveAbility(GEnemy, FourCC("A001"))

    end)

end
MUDA = false
function MudaMuda()
    muda = normal_sound("muda")
    MUDA=true
    TimerStart(CreateTimer(), 3, false, function()
        UnitAddAbility(GEnemy, FourCC("A001"))
    end)
    TimerStart(CreateTimer(), 3.5, false, function()
        local i = 0
        SetUnitTimeScale(GEnemy, 3)
        TimerStart(CreateTimer(), 0.2, true, function()
            i = i + 1
            --print(i)
            SetUnitAnimationByIndex(GEnemy, 3)
            DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", GetUnitXY(GPlayer)))
            if i == 18 then
                DestroyTimer(GetExpiredTimer())
                SetUnitTimeScale(GEnemy, 1)

                TimerStart(CreateTimer(), 0.2, false, function()
                    SetUnitAnimationByIndex(GEnemy, 3)
                    TimerStart(CreateTimer(), 0.4, false, function()
                        DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", GetUnitXY(GPlayer)))
                    end)
                    TimerStart(CreateTimer(), 0.6, false, function()
                        UnitRemoveAbility(GEnemy, FourCC("A001"))
                        AddSpecialEffect("Objects\\Spawnmodels\\Undead\\UndeadBlood\\UndeadBloodAbomination.mdl",GetUnitXY(GPlayer))
                        ShowUnit(GPlayer,false)
                        MUDA = false
                    end)
                end)
            end
        end)
    end)
end