---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.10.2021 23:42
---
BoPeeBo = { 0, 1, 5, 6, 10, 11, 12, 15, 16, 17,
            20-1, 21-1, 21.5, 22, 25, 26, 26.5, 27
}
ArroPos = { 4, 3, 10, 9, 4, 3, 2, 10, 9, 8,
            2, 3, 4, 1, 8, 9, 10, 7
}