---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.11.2021 15:29
---

function BugSpeed()
    local table = {
        1,
        0.998,
        0.997,
        0.996,
        0.995,
        0.994,
        0.993,
        0.992,
        0.991,
        0.99, --10
        0.989,
        0.988,
        0.987,
        0.986,
        0.985,
        0.98,
        0.978,
        0.978,
        0.978,
        0.978, --20
        0.976,
        0.975,
        0.975,
        0.975,
        0.975,
        0.975,
        0.975,
        0.98,
        0.99,
        1, --30
        0.997,
        0.995,
        0.994,
        0.993,
        0.992,
        0.991,
        0.99,
        0.99,
        0.99,
        0.989, -- 40
        0.988,
        0.987,
        0.986,
        0.985, --45
    }
    local t = 0
    local k = 1
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        t = t + TIMER_PERIOD64

        if t >= 60 then
            print("скорость игры изменена на "..table[k])
            t=0
            DelayPerTime=table[k]
            k=k+1
        end
    end)
end