---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.11.2021 16:12
---

G_OSKEY_LEFT = OSKEY_A
G_OSKEY_RIGHT = OSKEY_D
G_OSKEY_UP = OSKEY_W
G_OSKEY_DOWN = OSKEY_S
GKeyTrig = {}

function CreateKeyTrigger(keys)
    local i = 0
    for v, k in pairs(keys) do
        i = i + 1

        GKeyTrig[i] = CreateTrigger()
        local key = k.key
        TriggerAddAction(GKeyTrig[i], function()
            KeyPressed(v)
        end)
        for v, k in pairs(key) do
            BlzTriggerRegisterPlayerKeyEvent(GKeyTrig[i], Player(0), k, 0, true)
            BlzTriggerRegisterPlayerKeyEvent(GKeyTrig[i], Player(0), k, 0, false)
        end
    end
end

function DestroyKeyTrigger()
    for i = 1, #GKeyTrig do
        DestroyTrigger(GKeyTrig[i])
        --print("триггер уничтожен",i)
    end
end

function
CreateSettingsPanel()
    local selfBox = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "StandardFrameTemplate", 0)
    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", selfBox, "StandardFrameTemplate", 0)
    local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    --BlzFrameSetParent(tooltip, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --BlzFrameSetParent(backdrop, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAbsPoint(selfBox, FRAMEPOINT_CENTER, 0.4, 0.3)
    BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_CENTER, 0.4, 0.3)
    --    BlzFrameSetAllPoints(tooltip,selfBox)
    BlzFrameSetSize(tooltip, 0.2, 0.3)
    BlzFrameSetSize(backdrop, 0.2, 0.3)
    BlzFrameSetSize(text, 0.2 * .75, 0.3 * .9)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetAlpha(backdrop, 150)
    BlzFrameSetText(text, "Настройка управления")
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.04, 0.0)
    BlzFrameSetVisible(tooltip, true)

    -- Создаём бекдропы
    local sx, sy, step = 0.00, 0.08, 0.06
    CreateArrowTemplate(sx, sy, "Arrows\\5", tooltip) --влево
    CreateArrowTemplate(sx, sy - step, "Arrows\\8", tooltip)--вправо
    CreateArrowTemplate(sx, sy - step * 2, "Arrows\\3", tooltip)--вверх
    CreateArrowTemplate(sx, sy - step * 3, "Arrows\\1", tooltip) --вниз

    --создаём поля ввода
    --CreateBox(sx+0.15,sy,tooltip,"A")
    --CreateBox(sx+0.15,sy-step,tooltip,"D")
    --CreateBox(sx+0.15,sy-step*2,tooltip,"W")
    --CreateBox(sx+0.15,sy-step*3,tooltip,"S")
    local InputForChange=nil
    CreateGlueWisHotkey(sx + 0.15, sy, nil, tooltip, "A", function()
        print("Нажмите на клавишу, чтобы сменить её")
    end)

end

function CreateArrowTemplate(x, y, texture, parent)
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', parent, '', 0)
    BlzFrameSetTexture(image, texture, 0, true)
    BlzFrameSetPoint(image, FRAMEPOINT_LEFT, parent, FRAMEPOINT_LEFT, x, y)
    BlzFrameSetSize(image, 0.08, 0.08)
end

function CreateGlueWisHotkey(x, y, texture, parent, stringKey, call)
    local NextPoint = 0.039
    if not texture then
        texture = "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn"
    end
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", SelfFrame, "", 0)


    BlzFrameSetText(text, stringKey)
    BlzFrameSetSize(text, 0.01, 0.01)
    BlzFrameSetScale(text,2)

    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, SelfFrame, FRAMEPOINT_CENTER, -0.03, 0.0)
    --BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))


    --BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, NextPoint, NextPoint)

    --BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, x,y)
    BlzFrameSetPoint(SelfFrame, FRAMEPOINT_LEFT, parent, FRAMEPOINT_LEFT, x, y)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        call()
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)

    end)
end