---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.11.2021 17:13
---
GMissCount=0
function CreateMissCounter()

    local frame = CreateAndPlayGif(0.83, 0.49, "gif\\gargoule_page_000", 0.04)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", frame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "0")
    BlzFrameSetScale(text, 2)
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, frame, FRAMEPOINT_LEFT, 0.025, 0.0) --Сдвиг очков относительно эмблемы

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
            BlzFrameSetText(text, I2S(R2I(GMissCount)))
    end)
end