---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.12.2021 12:51
---
function CreateRSG()
    TimerStart(CreateTimer(), 0.8, false, function()
        CreateReady()
    end)
    TimerStart(CreateTimer(), 1.3, false, function()
        CreateSet()
    end)
    TimerStart(CreateTimer(), 1.8, false, function()
        CreateGo()
    end)
end

function CreateReady()
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(image, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(image, "ready", 0, true)
    BlzFrameSetSize(image, 0.32, 0.16)
    BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, 0.4, 0.4)
    local alpha = 255
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        alpha = alpha - 10
        BlzFrameSetAlpha(image, R2I(alpha))
        if alpha <= 120 then
            DestroyTimer(GetExpiredTimer())
            BlzDestroyFrame(image)
        end
    end)
end

function CreateSet()
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(image, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(image, "set", 0, true)
    BlzFrameSetSize(image, 0.32, 0.16)
    BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, 0.4, 0.4)
    local alpha = 255
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        alpha = alpha - 10
        BlzFrameSetAlpha(image, R2I(alpha))
        if alpha <= 120 then
            DestroyTimer(GetExpiredTimer())
            BlzDestroyFrame(image)
        end
    end)
end

function CreateGo()
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(image, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(image, "go", 0, true)
    BlzFrameSetSize(image, 0.32, 0.32)
    BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, 0.4, 0.4)
    local alpha = 255
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        alpha = alpha - 10
        BlzFrameSetAlpha(image, R2I(alpha))
        if alpha <= 120 then
            DestroyTimer(GetExpiredTimer())
            BlzDestroyFrame(image)
        end
    end)
end