---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.11.2021 14:23
---
function CreateSelections(frame_relative, timed)

    local new_Frame = BlzCreateFrameByType("SPRITE", "justAName", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "WarCraftIIILogo", 0)
    BlzFrameSetParent(new_Frame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetPoint(new_Frame, FRAMEPOINT_BOTTOMLEFT, frame_relative, FRAMEPOINT_BOTTOMLEFT, 0.02, 0.02)
    --BlzFrameSetAbsPoint(new_Frame,FRAMEPOINT_CENTER,0.4,0.6)
    BlzFrameSetSize(new_Frame, 1., 1.)
    BlzFrameSetScale(new_Frame, 1.)
    BlzFrameSetModel(new_Frame, "selecter5.mdx", 0)

    TimerStart(CreateTimer(), timed, false, function()
        DestroyTimer(GetExpiredTimer())
       BlzDestroyFrame(new_Frame)
    end)
end
