---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 25.11.2021 0:50
---
function CreateAndPlayGif(x, y,path)
    local gifPath = path--"gif\\gargoule_page_000"
    local endFrame = 8
    local s = 1
    local gif = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local firstShow = false
    local size=0.04
    BlzFrameSetParent(gif, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(gif, gifPath .. 0, 0, true)
    BlzFrameSetSize(gif, size, size)
    BlzFrameSetAbsPoint(gif, FRAMEPOINT_TOP, x, y)
    BlzFrameSetVisible(gif, false)
    TimerStart(CreateTimer(), TIMER_PERIOD*2, true, function()
        if not firstShow then
            firstShow = true
            BlzFrameSetVisible(gif, true)
        end
        BlzFrameSetTexture(gif, gifPath .. I2S(R2I(s)), 0, true)
        --print(s)
        s=s+1
        if s>endFrame then
            s=1
        end
    end)
    return gif
end