---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2021 15:45
---
EMPTY = nil
IcoOfSongsLocked = {}
LockedState = { true, false, false, false, false }
PointForUnlock = { 0, 25000, 150000, 10000, 70000 }
SongCompleteCount = 1
SongCompleted = { false, false, false, false, false, }
function CreateSongMenus()
    CreateHandArrowWPulse(-0.05, 0.4)
    ttBox, _, ttText = CreateToolTipBox()
    local nextPoint = 0.04
    EMPTY, IcoOfSongsLocked[1] = CreateSimpleFrameGlue(-0.1, 0.4 - nextPoint * 0, "BTNsos", 1, function()
        StartNewSong(1)
    end)

    EMPTY, IcoOfSongsLocked[2] = CreateSimpleFrameGlue(-0.1, 0.4 - nextPoint * 2, "lockedicon", 2, function()
        if LockedState[2] then
            StartNewSong(2)
        else
            --print("Необходимо", PointForUnlock[2], "очков")
            normal_sound("Sound\\Interface\\Error")
        end
    end)

    EMPTY, IcoOfSongsLocked[3] = CreateSimpleFrameGlue(-0.1, 0.4 - nextPoint * 4, "lockedicon", 3, function()
        if LockedState[3] then
            StartNewSong(3)
        else
            --print("Необходимо", PointForUnlock[3], "очков")
            normal_sound("Sound\\Interface\\Error")
        end

    end)

    EMPTY, IcoOfSongsLocked[4] = CreateSimpleFrameGlue(-0.1, 0.4 - nextPoint * 1, "lockedicon", 4, function()
        if LockedState[4] then
            StartNewSong(4)
        else
            --print("Необходимо", PointForUnlock[3], "очков")
            normal_sound("Sound\\Interface\\Error")
        end

    end)
    EMPTY, IcoOfSongsLocked[5] = CreateSimpleFrameGlue(-0.1, 0.4 - nextPoint * 3, "lockedicon", 5, function()
        if LockedState[5] then
            StartNewSong(5)
        else
            --print("Необходимо", PointForUnlock[3], "очков")
            normal_sound("Sound\\Interface\\Error")
        end

    end)
end

function CreateHandArrowWPulse(x, y)
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(image, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(image, "hand", 0, true)
    BlzFrameSetSize(image, 0.08, 0.08)
    BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, x, y)
    GHandY = y
    local i = 0
    TimerStart(CreateTimer(), 0.1, true, function()
        i = i + 1
        BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, x + (math.sin(i) / 100), GHandY)
    end)
end

function StartNewSong(number)
    local heroTable = {
        FourCC("Hart"), --артас
        FourCC("O000"), -- Таурен
        nil,-- хенк
        FourCC("U000"), -- детерок
        nil, --демонесса
    }
    if not MUDA then
        if not restartReady then
            return
        else
            if IsUnitHidden(GPlayer) then
                AddSpecialEffect("Abilities\\Spells\\Human\\Resurrect\\ResurrectTarget.mdl", GetUnitXY(GPlayer))
                SetUnitAnimation(GEnemy, "spell")
            end
            ShowUnit(GPlayer, true)
            restartReady = false
            GameIsDefeat = false
            GHP = 50
            if heroTable[number] then
                ReplaceHeroForCurrentSong(number, heroTable[number])
            else
                --print(number,"Героя нет в базе, будет артас")
            end
            BreakCurrentLevel()
            SetUnitAnimation(GEnemy, "Stand Ready")
            SetUnitAnimation(GPlayer, "Stand Ready")
            StarAllSound(number)
            TimerStart(CreateTimer(), 0.3, false, function()
                DestroyTimer(GetExpiredTimer())
                restartReady = true
            end)
        end
    end
end

function ReplaceHeroForCurrentSong(number, id)
    if number ~= SONG then
        local x, y = GetUnitXY(GEnemy)
        ShowUnit(GEnemy, false)
        KillUnit(GEnemy)
        CreateAndFallUnit(id, x, y)
    else
        --print("замена персонажа не требуется")
    end
end

function CreateAndFallUnit(id, x, y)
    GEnemy = CreateUnit( Player(0),id, x, y, 90)
    UnitAddAbility(GEnemy,FourCC("Aloc"))
    SetUnitFacing(GEnemy,AngleBetweenUnits(GEnemy,GPlayer))
    SetUnitZ(GEnemy, 1500)
    SetUnitAnimation(GEnemy, "death")
    normal_sound("FallSuperHero")
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        local z = GetUnitZ(GEnemy)
        SetUnitZ(GEnemy, z - 50)
        --print(z)

        if z <= 50 then
            --print("приземлился")
            --DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", x, y))

            PlayerSeeNoiseInRangeTimed(1,x,y)
            DestroyTimer(GetExpiredTimer())
        end
    end)
end