---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.11.2021 0:52
---
function CreateGameSpeedIndicator()
    local ico = "UI\\Widgets\\Console\\Human\\CommandButton\\human-button-lvls-overlay"
    local frame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(frame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(frame, ico, 0, true)
    BlzFrameSetSize(frame, 0.04, 0.04)
    BlzFrameSetAbsPoint(frame, FRAMEPOINT_CENTER, 0.83, 0.51)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", frame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "GameSpeed")
    BlzFrameSetScale(text, 1)
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, frame, FRAMEPOINT_LEFT, 0.05, 0.0) --Сдвиг очков относительно эмблемы

    local textGS = BlzCreateFrameByType("TEXT", "ButtonChargesText", frame, "", 0)
    BlzFrameSetParent(textGS, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(textGS, GameSpeed)
    BlzFrameSetScale(textGS, 1)
    BlzFrameSetPoint(textGS, FRAMEPOINT_LEFT, frame, FRAMEPOINT_LEFT, 0.01, 0.0) --Сдвиг очков относительно эмблемы

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        BlzFrameSetText(textGS, DelayPerTime)
    end)

end

