---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.11.2021 14:34
---
---
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()

        TimerStart(CreateTimer(), 1, false, function()
            if not BlzLoadTOCFile("war3mapimported\\so.toc") then
                print("eeloadtoc")
            end
            --CreateBox(nil, nil, "up")
            --CreateSettingsPanel()

        end)

    end
end

function CreateBox(x, y, parent,flag)
    local editbox = BlzCreateFrame("EscMenuEditBoxTemplate", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0) --create the box
    local eventHandler
    BlzFrameSetText(editbox, flag)
   -- BlzFrameSetAbsPoint(editbox, FRAMEPOINT_CENTER, x, y) -- pos the box
    BlzFrameSetPoint(editbox,FRAMEPOINT_LEFT,parent,FRAMEPOINT_LEFT,x, y)
    BlzFrameSetSize(editbox, 0.04, 0.04) --set the boxs size

    eventHandler = CreateTrigger() --Create the FRAMEEVENT_EDITBOX_ENTER trigger
    BlzTriggerRegisterFrameEvent(eventHandler, editbox, FRAMEEVENT_EDITBOX_ENTER)
    TriggerAddAction(eventHandler, function()
        --print("EditBoxEnter:")
        --print(BlzGetTriggerFrameText())
        --print(GetPlayerName(GetTriggerPlayer()))
    end)

    eventHandler = CreateTrigger() --Create the FRAMEEVENT_EDITBOX_TEXT_CHANGED trigger
    BlzTriggerRegisterFrameEvent(eventHandler, editbox, FRAMEEVENT_EDITBOX_TEXT_CHANGED)

    TriggerAddAction(eventHandler, function()
        DisableTrigger(GetTriggeringTrigger())
        BlzFrameSetText(editbox, "")
        BlzFrameSetText(editbox, BlzGetTriggerFrameText())
        print("текст измненён на", BlzGetTriggerFrameText())
        EnableTrigger(GetTriggeringTrigger())
    end)

end