---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.11.2021 13:23
---
function ControlGameCam()
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        if not MUDA then
            CameraSetupApplyForPlayer(false, gg_cam_Camera_001, Player(0), 1.00)

        end
    end)
end