---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.10.2021 18:44
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), .5, false, function()
            Preload("Inst")
            Preload("Voices")
            Preloader("Inst")
            Preloader("Voices")
            ReturnFPS()
            HideEverything()

        end)
        TimerStart(CreateTimer(), 1, false, function()
            StarAllSound()

            DestroyTimer(GetExpiredTimer())
        end)
    end
end

TIMER_PERIOD = 1 / 32
TIMER_PERIOD64 = 1 / 64
function StarAllSound()
    local x, y = GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0))
    normal_sound("All", x, y)
    TimerStart(CreateTimer(), 0.011, false, function()
        --normal_sound("Voices", x, y)
        -- print("голос")
    end)

    TimerStart(CreateTimer(), 0.01, false, function()
        --normal_sound("Inst", x, y)
        -- print("фон")
    end)
    StartArrow()
end

function StartArrow()
    for i = 1, #BoPeeBo do
        TimerStart(CreateTimer(), BoPeeBo[i]*.5, false, function()
            local step=nil
            if ArroPos[i] then
                step=ArroPos[i]
            else
                --print("таблица не заполнена, рандомимся ")
                step={1,2,3,4,6,8,9,10}
                step=step[GetRandomInt(1,#step)] --никогда так не делайте
            end
            CreateArrowAndUp( 0.01,step)
            --print(BoPeeBo[i])
            DestroyTimer(GetExpiredTimer())
        end)
    end
end

function CreateArrowAndUp(speed, pozX)
    local texture = "ReplaceableTextures\\CommandButtons\\BTNCryptFiendUnBurrow.blp"
    local x, y = 0.08, 0
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local step = 0.08
    local r=GetRandomInt(0,3)
    local randomStep=(step*pozX)-x

    BlzFrameSetAlpha(image, 0)
    BlzFrameSetTexture(image, texture, 0, true)
    BlzFrameSetSize(image, 0.04, 0.04)
    BlzFrameSetParent(image, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, randomStep, y)

    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        y = y + speed
        BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, randomStep, y)
        if y >= 0.6 then
            DestroyTimer(GetExpiredTimer())
            BlzFrameSetVisible(image, false)

        end
    end)
end