---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 20.10.2021 22:26
---
GPoint = 0
function CreatePointInterFace()
    local ico = "war3mapImported\\xgm"
    local frame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(frame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(frame, ico, 0, true)
    BlzFrameSetSize(frame, 0.04, 0.04)
    BlzFrameSetAbsPoint(frame, FRAMEPOINT_CENTER, 0.83, 0.55)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", frame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "0")
    BlzFrameSetScale(text, 2)
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, frame, FRAMEPOINT_LEFT, 0.025, 0.0) --Сдвиг очков относительно эмблемы
    GPointTextFrame = text
    --updatePoint
    local p=GPoint
    local PLerp=p
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        p = GPoint
        local speed=1--p-PLerp --8 быстро 1 медленно
        if p-PLerp<=100 then
            speed=20
        else
            speed=1
        end
        PLerp = math.lerp(PLerp, p, TIMER_PERIOD64 * speed)
        local descriptions = I2S(R2I(PLerp))
        --if PLerp> 1 then
            BlzFrameSetText(GPointTextFrame, I2S(R2I(descriptions+1)))
        --end
    end)
end

function AddPoint(points)
    GPoint = GPoint + points

    --math.lerp(lerp)
    --BlzFrameSetText(GPointTextFrame, descriptions)
    if points > 0 then
        CreateFlyPoint(points)
    end
    --print(enc(I2S(GPoint)))
    SaveResult(enc(I2S(GPoint))) --сохраняем очки каждый чих

    if not LockedState[2] then
        if GPoint >= PointForUnlock[2] then
            --and SongCompleteCount>=3
            BlzFrameSetTexture(IcoOfSongsLocked[2], "BTNzavod", 0, true)
            CreateSelections(IcoOfSongsLocked[2], 5)
            LockedState[2] = true
            normal_sound("Sound\\Interface\\BattleNetDoorsStereo2")
        end

    end
    if not LockedState[3] then
        if GPoint >= PointForUnlock[3] and SongCompleteCount >= 5 then
            BlzFrameSetTexture(IcoOfSongsLocked[3], "BTNhank", 0, true)
            LockedState[3] = true
            CreateSelections(IcoOfSongsLocked[3], 5)
            normal_sound("Sound\\Interface\\BattleNetDoorsStereo2")
        end
    end
    if not LockedState[4] then
        if GPoint >= PointForUnlock[4] and SongCompleteCount >= 2 then
            BlzFrameSetTexture(IcoOfSongsLocked[4], "BTNFresh", 0, true)
            LockedState[4] = true
            CreateSelections(IcoOfSongsLocked[4], 5)
            normal_sound("Sound\\Interface\\BattleNetDoorsStereo2")
        end
    end
    if not LockedState[5] then
        if GPoint >= PointForUnlock[5] and SongCompleteCount >= 4 then
            BlzFrameSetTexture(IcoOfSongsLocked[5], "BTNMilf", 0, true)
            LockedState[5] = true
            CreateSelections(IcoOfSongsLocked[5], 5)
            normal_sound("Sound\\Interface\\BattleNetDoorsStereo2")
        end
    end
end

function CreateFlyPoint(descriptions)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    local x, y = 0.5, 0.3
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, descriptions)
    BlzFrameSetScale(text, 4)
    BlzFrameSetAbsPoint(text, FRAMEPOINT_CENTER, x, y)
    local reverse = false
    --local hide = false
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        if not reverse then
            y = y + 0.002
        else
            y = y - 0.004
            x = x + 0.004
            BlzFrameSetAlpha(text, R2I(y * 102))
        end
        if y > 0.35 then
            reverse = true
        end

        BlzFrameSetAbsPoint(text, FRAMEPOINT_CENTER, x, y)
        if reverse and y <= 0.3 then
            --print("destroy")
            DestroyTimer(GetExpiredTimer())
            BlzDestroyFrame(text)
        end

    end)
end

