---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bear.
--- DateTime: 31.10.2021 21:31
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        AllPreload()
    end
end

function AllPreload()
    StopSound(normal_sound("All"), true, false)
    StopSound(normal_sound("zavodila"), true, false)
end