---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.11.2021 23:01
---
function SongCamera(data)
    if data <= 4 then
        --print("на артаса")
        SetUnitLookAt(GJaina,"bone_head",GEnemy,0,0,120)
        TimerStart(CreateTimer(), 0.1, false, function()
            PanCameraToTimed(GetUnitX(GEnemy), GetUnitY(GEnemy), 1)
            DestroyTimer(GetExpiredTimer())
        end)

    else
        --print("на пеона")
        SetUnitLookAt(GJaina,"bone_head",GPlayer,-120,0,120)
        PanCameraToTimed(GetUnitX(GPlayer), GetUnitY(GPlayer), 1)
    end
end