---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 22.11.2021 1:46
---
function CreateSpaceForRestart()
    SpaceRegister()
    local NextPoint = 0.039
    local texture = "EmptySpace"
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", SelfFrame, "", 0)

    BlzFrameSetText(text, "SPACE - перезапуск текущей песни")
    BlzFrameSetSize(text, NextPoint * 7, 0.01)
    BlzFrameSetScale(text, 1)
    BlzFrameSetTextColor(text, BlzConvertColor(255, 0, 0, 0))

    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, SelfFrame, FRAMEPOINT_CENTER, 0.05, 0.0)

    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, NextPoint * 8, NextPoint)

    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, 0.4, 0.01)
    --BlzFrameSetPoint(SelfFrame, FRAMEPOINT_LEFT, parent, FRAMEPOINT_LEFT, x, y)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()

        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        StartNewSong(SONG)
    end)
end

function SpaceRegister()
    local thisTrig = CreateTrigger()
    BlzTriggerRegisterPlayerKeyEvent(thisTrig, Player(0), OSKEY_SPACE, 0, true)
    TriggerAddAction(thisTrig, function()
        StartNewSong(SONG)
    end)
end