---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.10.2021 17:02
---

function CreateSquack(x,y)
    local image = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local next = 1
    BlzFrameSetAlpha(image, 0)
    BlzFrameSetTexture(image, "Shvaks\\" .. next, 0, true)
    BlzFrameSetSize(image, 0.16, 0.08)
    BlzFrameSetParent(image, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAbsPoint(image, FRAMEPOINT_CENTER, x,y)
    TimerStart(CreateTimer(), 1/32, true, function()
        next = next + 1
        BlzFrameSetTexture(image, "Shvaks\\" .. next, 0, true)
        if next == 5 then
            DestroyTimer(GetExpiredTimer())
            local alpha = 128
            TimerStart(CreateTimer(), 1 / 32, true, function()
                alpha = alpha - 30
                if alpha <= 0 then
                    DestroyTimer(GetExpiredTimer())
                    BlzDestroyFrame(image)
                else
                    BlzFrameSetAlpha(image, alpha)
                end


            end)
        end
    end)
end