---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.11.2021 17:22
---
---
Taurens = {}
function InitTaurens()
    Taurens[1] = BlzCreateUnitWithSkin(Player(PLAYER_NEUTRAL_PASSIVE), FourCC("o001"), -155.8 - 300, 31.8, 0.000, FourCC("o001"))
    Taurens[2] = BlzCreateUnitWithSkin(Player(PLAYER_NEUTRAL_PASSIVE), FourCC("o001"), -135.0 - 300, -227.1, 0.000, FourCC("o001"))
    SetUnitMoveSpeed(Taurens[1], 100)
    SetUnitMoveSpeed(Taurens[2], 100)
end

function MoveTaurens()
    IssuePointOrder(Taurens[1], "move", -155.8, 31.8)
    IssuePointOrder(Taurens[2], "move", -135.0, -227.1)
end

function MoveTaurensBack()
    IssuePointOrder(Taurens[1], "move", -155.8 - 500, 31.8)
    IssuePointOrder(Taurens[2], "move", -135.0 - 500, -227.1)
end

function TaurenStomp()
    --local _,_,t=FindUnitOfType(FourCC("o001"))
    for i = 1, #Taurens do
        SetUnitAnimation(Taurens[i], "Attack Slam")
        QueueUnitAnimation(Taurens[i], "Stand")
    end
    TimerStart(CreateTimer(), 0.2, false, function()
        PlayerSeeNoiseInRangeTimed(0.2)

    end)
end