---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.12.2021 23:43
---
function StartFirstCinema()
    local table1 = {
        L("что в конце концов главное не то, что у тебя в кармане, а то что на душе", "in the end, the important thing is not what you have in your pocket, and the fact that his soul"),
        L("что у меня теперь нет ни счастья, ни несчастья", "now I have neither happiness nor misery"),
        L("что, мол, все это так, да не так.", "that, well, it's all so, so wrong"),
        L("ты знаешь, ты мне не друг, мне от тебя ничего не нужно, только не лезь в мою жизнь", "you know, you're not my friend, I want nothing from you, just stay out of my life"),
        L("что мол так, да так, ну просто супер, но в душе хотелось бы, что бы это было не так", "very well, Oh, well, just super, but in my heart I wish it wasn't so"),
        L("что ты хоть и красивый, но на фиг не нужен. А он мне и говорит, а зачем я тебе нужен? В итоге он поехал домой, а я остался с кучей цветов, шарами и огромным букетом из 101 розы", "what are you, though beautiful, but not needed in Fig. And he says to me, why do you need me? As a result, he went home, and I was left with a bunch of flowers, balloons and a huge bouquet of 101 roses"),
        L("у нет, так не пойдет!", "no, it won't do"),
        L("сходи в город, найди себе жену, чтобы в хозяйстве была помощница...", "go to the city, find yourself a wife so that there is an assistant in the household..."),
        L("вот ты говоришь, что, мол, счастье — это когда ничего не болит...", "here you say that, they say, happiness is when nothing hurts..."),
    }
    local table2 = {
        L("А ты как всегда - на веселе", "And you, as always, are tipsy"),
        L("Эти твои шуточки", "These jokes of yours"),
        L("Остришь, как всегда", "You're making jokes, as always"),

    }

    local NamePeon = L("Пеонетти", "Peonetty")
    local NameJaina = L("Джайна", "Jaina")
    local NamePapirus = L("Папирус", "Papyrus")
    local NameArthas = L("Артас", "Arthas")

    SetCameraBoundsToRectForPlayerBJ(Player(0), bj_mapInitialPlayableArea)
    HideGameUnits(false)
    CreateFakeUnits()
    ClearMapMusicBJ()
    PlayMusicBJ("LuvSeemee")
    SetMusicVolumeBJ(15)


    CinematicModeBJ(true, GetPlayersAll()) -- перенёс в инит
    CameraSetupApplyForPlayer(false, gg_cam_FirstCinema, Player(0), 1.00)
    SetCameraTargetControllerNoZForPlayer(Player(0), FakePeon, 0, 0, true)

    TimerStart(CreateTimer(), 2, false, function()

        local gg_trg_ESC = CreateTrigger()
        TriggerRegisterPlayerEventEndCinematic(gg_trg_ESC, Player(0))
        TriggerAddAction(gg_trg_ESC, function()
            if not GameISStarted then
                StartGame()
            end
            GameISStarted = true
            DisableTrigger(GetTriggeringTrigger())
        end)
        --Фековые юниты идут из точтки (старта) в точку 0,0 джайна идёт в точку 0,50
        local SpeechInWalk = {
            L("И тут я ему и говорю, тут длинная рандомная фраза 7 сек", "And then I tell him, "), --Peonetty
            L("Эти твои шуточки и тут тоже рандомная но короткая враза на 4 сек", "These jokes of yours"), --Jaina
            L("Но скажи, а мы скоро уже туда придём, я, кажется, уже натерла ножки...", "But tell me, and we'll be there soon, I think I've already rubbed my legs..."),--Jaina
            L("Я не просил тебя идти со мной, ты можешь пойти назад в любой момент", "I didn't ask you to come with me, you can go back at any time"),--Peonetty
            L("Какой же ты иногда грубый мужлан, но я чувсвую, что это мой долг - поддержать тебя, ведь ты всё таки мой...", "What a rude bumpkin you are sometimes, but I feel that it is my duty to support you, because you are still my..."),--Jaina
            L("О, мы уже пришли, посмотри, это же Папирус. Привет, Папирус!", "Oh, we've already come, look, it's Papyrus. Hello, Papyrus!"),--Peonetty в момонт когда пошли к скелету
            L("Папирус, пойдёшь с нами?", "Papyrus, will you come with us?"),--Jaina Джайна останавливается, на секунду
            L("Оу, как приятно, что позвали, но я в другой раз, удачи вам", "Oh, how nice to be called, but I'll do it another time, good luck to you"),--Papyrus -- Это скелет который стоит при входе
            L("Посмотрите на него, явился, АХАХАХХ, и ещё подружку с собой взял", "Look at him, he showed up, AHAHAHH, and he also took his girlfriend with him"),--Arthas Артас начинает говорить когда пеон ещё идёт
            L("Как же ты ничтожен, жалкий батрак", "How insignificant you are, you miserable peon"),--Arthas пеон уже должен быть на точке во время этой фразы
            L("И это говорит мне тот, кто пронёс оружие на музыкальную битву?", "And this is what the one wh-o brought the weapon to the musical battle tells me?"),--Peonetty, пеон и джайна проигрывают анимацию Stand Ready
            L("Ну всё, ты сам напросился!!!", "Well, that's it, you asked for it!!!"),--Arthas через 2 сек после это фразы Кастом скрипт StartGame(), фейковые юниты должны быть скрыты, потому что отоброзяться игровые

        }

        if GameISStarted then
            return
        end
        CinematicFadeBJ(bj_CINEFADETYPE_FADEIN, 7, "ReplaceableTextures\\CameraMasks\\Black_mask.blp", 0, 0, 0, 0.00)
        math.randomseed(123)
        TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("o002"), NamePeon, GetRectCenter(GetPlayableMapRect()), nil, L("И тут я ему и говорю, ", "And then I tell him, ") .. table1[GetRandomInt(1, #table1)], bj_TIMETYPE_ADD, 0, false)

        TimerStart(CreateTimer(), 8, false, function()
            if GameISStarted then
                return
            end
            TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("Hjai"), NameJaina, GetRectCenter(GetPlayableMapRect()), nil, table2[GetRandomInt(1, #table2)], bj_TIMETYPE_ADD, 0, false)
            TimerStart(CreateTimer(), 4, false, function()
                if GameISStarted then
                    return
                end
                TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("Hjai"), NameJaina, GetRectCenter(GetPlayableMapRect()), nil, L("Но скажи, а мы скоро уже туда придём, я, кажется, уже натерла ножки...", "But tell me, and we'll be there soon, I think I've already rubbed my legs..."), bj_TIMETYPE_ADD, 0, false)
                TimerStart(CreateTimer(), 6, false, function()
                    if GameISStarted then
                        return
                    end
                    TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("o002"), NamePeon, GetRectCenter(GetPlayableMapRect()), nil, L("Я не просил тебя идти со мной, ты можешь пойти назад в любой момент", "I didn't ask you to come with me, you can go back at any time"), bj_TIMETYPE_ADD, 0, false)
                    TimerStart(CreateTimer(), 6, false, function()
                        if GameISStarted then
                            return
                        end
                        TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("Hjai"), NameJaina, GetRectCenter(GetPlayableMapRect()), nil, L("Какой же ты иногда грубый мужлан, но я чувсвую, что это мой долг - поддержать тебя, ведь ты всё таки мой...", "What a rude bumpkin you are sometimes, but I feel that it is my duty to support you, because you are still my..."), bj_TIMETYPE_ADD, 0, false)
                        TimerStart(CreateTimer(), 6, false, function()
                            if GameISStarted then
                                return
                            end
                            TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("o002"), NamePeon, GetRectCenter(GetPlayableMapRect()), nil, L("О, мы уже пришли, посмотри, это же Папирус. Привет, Папирус!", "Oh, we've already come, look, it's Papyrus. Hello, Papyrus!"), bj_TIMETYPE_ADD, 0, false)
                            TimerStart(CreateTimer(), 3, false, function()
                                if GameISStarted then
                                    return
                                end
                                TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("Hjai"), NameJaina, GetRectCenter(GetPlayableMapRect()), nil, L("Папирус, пойдёшь с нами?", "Papyrus, will you come with us?"), bj_TIMETYPE_ADD, 0, false)
                                BlzPauseUnitEx(FakeJaina, true)
                                TimerStart(CreateTimer(), 3, false, function()
                                    if GameISStarted then
                                        return
                                    end
                                    BlzPauseUnitEx(FakeJaina, false)
                                    TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("uske"), NamePapirus, GetRectCenter(GetPlayableMapRect()), nil, L("Оу, как приятно, что позвали, но я в другой раз, удачи вам", "Oh, how nice to be called, but I'll do it another time, good luck to you"), bj_TIMETYPE_ADD, 0, false)
                                    TimerStart(CreateTimer(), 8, false, function()
                                        if GameISStarted then
                                            return
                                        end
                                        SetUnitLookAt(FakeJaina, "bone_head", FakeArthas, 0, 0, 120)
                                        SetUnitLookAt(FakePeon, "bone_head", FakeArthas, 0, 0, 120)
                                        TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("H000"), NameArthas, GetRectCenter(GetPlayableMapRect()), nil, L("Посмотрите на него, явился, АХАХАХХ, и ещё подружку с собой взял", "Look at him, he showed up, AHAHAHH, and he also took his girlfriend with him"), bj_TIMETYPE_ADD, 0, false)
                                        TimerStart(CreateTimer(), 6, false, function()
                                            if GameISStarted then
                                                return
                                            end
                                            TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("H000"), NameArthas, GetRectCenter(GetPlayableMapRect()), nil, L("Как же ты ничтожен, жалкий батрак", "How insignificant you are, you miserable peon"), bj_TIMETYPE_ADD, 0, false)
                                            TimerStart(CreateTimer(), 6, false, function()
                                                if GameISStarted then
                                                    return
                                                end
                                                SetUnitAnimation(FakePeon, "Stand Ready")
                                                SetUnitAnimationByIndex(FakeJaina, 31)
                                                TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("o002"), NamePeon, GetRectCenter(GetPlayableMapRect()), nil, L("И это говорит мне тот, кто пронёс оружие на музыкальную битву?", "And this is what the one who brought the weapon to the musical battle tells me?"), bj_TIMETYPE_ADD, 0, false)
                                                TimerStart(CreateTimer(), 6, false, function()
                                                    if GameISStarted then
                                                        return
                                                    end
                                                    TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("H000"), NameArthas, GetRectCenter(GetPlayableMapRect()), nil, L("Ну всё, ты сам напросился!!!", "Well, that's it, you asked for it!!!"), bj_TIMETYPE_ADD, 0, false)
                                                    TimerStart(CreateTimer(), 3.5, false, function()
                                                        if GameISStarted then
                                                            return
                                                        end
                                                        StartGame()
                                                    end)
                                                end)
                                            end)
                                        end)
                                    end)
                                end)
                            end)
                        end)
                    end)
                end)
            end)
        end)
    end)

end

function HideGameUnits(state)
    ShowUnit(GJaina, state)
    ShowUnit(GPlayer, state)
    ShowUnit(GEnemy, state)
end

function CreateFakeUnits()
    local x, y = 2460, 0
    local xEnd, yEnd = 100, 0

    FakeJaina = CreateUnit(Player(0), FourCC("Hjai"), x + 80, y, 0)
    FakePeon = CreateUnit(Player(0), FourCC("opeo"), x, y, 0)
    FakeArthas = CreateUnit(Player(0), FourCC("Hart"), xEnd - 200, yEnd, 0)

    AddUnitAnimationProperties(FakeJaina, "cinematic", true)
    AddUnitAnimationProperties(FakePeon, "cinematic", true)
    SetUnitMoveSpeed(FakeJaina, 50)
    SetUnitMoveSpeed(FakePeon, 50)
    IssuePointOrder(FakeJaina, "move", xEnd, yEnd)
    IssuePointOrder(FakePeon, "move", xEnd, MoveY(yEnd, 30, 270))
end

function HideFakePlayer()
    ShowUnit(FakeJaina, false)
    ShowUnit(FakePeon, false)
    ShowUnit(FakeArthas, false)

end

GameISStarted = false
function StartGame()
    --print("Выворт исходной камеры")
    GameISStarted = true
    ClearMapMusicBJ()
    StopMusic(true)
    CinematicModeBJ(false, GetPlayersAll())
    CameraSetupApplyForPlayer(false, gg_cam_Camera_001, Player(0), 1.00)
    SetCameraBoundsToRectForPlayerBJ(Player(0), gg_rct_Region_000)
    HideFakePlayer()
    MUDA = false
    ready = false
    StarAllSound(1)
    HideGameUnits(true)
    HideEverything()
    ReturnFPS()
    MenuFrame()
    MUDA = false
    CreatePointInterFace()
    CreateGameSpeedIndicator()
    CreateSongMenus()
    CreateMissCounter()
    GifCat = CreateAndPlayGif(-0.092, 0.08, "gif\\CatGif\\frame_", 0.08, 157, false, 1 / 24, 1)
    ShuffleIcons(true)
    CreateHPBar("20")
    CreateHPBar("06")
    CreateHPBar("00")
    CreateVSIcons()
    ready = true
    AddPoint(S2I(LoadCode[0]))
    CreateSpaceForRestart()
    ControlGameCam()
end