---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.12.2021 23:43
---
function StartFirstCinema()
    local table1={
        "что в конце концов главное не то, что у тебя в кармане, а то что на душе",
        "что у меня теперь нет ни счастья, ни несчастья",
        "что, мол, все это так, да не так.",
        "ты мол, Вась, знаешь, ты мне не друг, мне от тебя ничего не нужно, только не лезь в мою жизнь",
        "что мол так, да так, ну просто супер, но в душе хотелось бы, что бы это было не так",
        "что ты хоть и красивый, но на фиг не нужен. А он мне и говорит, а зачем я тебе нужен? В итоге он поехал домой, а я остался с кучей цветов, шарами и огромным букетом из 101 розы",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    }

    SetCameraBoundsToRectForPlayerBJ(Player(0), bj_mapInitialPlayableArea)
    HideGameUnits()
    CreateFakeUnits()
    CinematicModeBJ(true, GetPlayersAll())
    CameraSetupApplyForPlayer(false, gg_cam_FirstCinema, Player(0), 1.00)
    SetCameraTargetControllerNoZForPlayer(Player(0), FakeJaina, 0, 0, true)

    TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("o002"), "Пеонетти", GetRectCenter(GetPlayableMapRect()), nil, "И тут я ему и говорю, ", bj_TIMETYPE_ADD, 0, false)
    TransmissionFromUnitTypeWithNameBJ(GetPlayersAll(), Player(0), FourCC("Hjai"), "Джайна", GetRectCenter(GetPlayableMapRect()), nil, "А ты забавный", bj_TIMETYPE_ADD, 0, false)
    TimerStart(CreateTimer(), 3, false, function()

    end)

    TimerStart(CreateTimer(), 2, false, function()
        CinematicFadeBJ(bj_CINEFADETYPE_FADEIN, 5, "ReplaceableTextures\\CameraMasks\\Black_mask.blp", 0, 0, 0, 0.00)

    end)

end

function HideGameUnits(state)
    ShowUnit(GJaina, state)
    ShowUnit(GPlayer, state)
    ShowUnit(GEnemy, state)
end

function CreateFakeUnits()
    local x, y = 2460, 0
    local xEnd, yEnd = 0, 0

    FakeJaina = CreateUnit(Player(0), FourCC("Hjai"), x, y, 0)
    FakePeon = CreateUnit(Player(0), FourCC("opeo"), x, y, 0)

    AddUnitAnimationProperties(FakeJaina, "cinematic", true)
    AddUnitAnimationProperties(FakePeon, "cinematic", true)
    SetUnitMoveSpeed(FakeJaina, 50)
    SetUnitMoveSpeed(FakePeon, 50)
    IssuePointOrder(FakeJaina, "move", xEnd, yEnd)
    IssuePointOrder(FakePeon, "move", xEnd, MoveY(yEnd, 30, 270))
end